name: CI of MujocoTactileSensorPlugin

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        build-type: [Debug, RelWithDebInfo]
        standalone: [standalone, colcon]
        mujoco-version: [3.0.0]
        include:
          - os: ubuntu-22.04
            build-type: RelWithDebInfo
            mujoco-version: 2.3.5 # 3.0.0
            standalone: colcon
          - os: ubuntu-22.04
            build-type: RelWithDebInfo
            mujoco-version: 2.3.7 # 3.0.0
            standalone: colcon
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup environment variables
        run: |
          set -e
          set -x
          if [ "${{ matrix.os }}" == "ubuntu-22.04" ] && \
             [ "${{ matrix.build-type }}" == "RelWithDebInfo" ] && \
             [ "${{ matrix.standalone }}" == "colcon" ] &&  \
             [ "${{ github.repository_owner }}" == "isri-aist" ] && \
             [ "${{ github.ref }}" == "refs/heads/main" ] && \
             [ "${{ matrix.mujoco-version }}" == "3.0.0"]
          then
            echo "UPLOAD_DOCUMENTATION=true" >> $GITHUB_ENV
            sudo apt-get install -qq doxygen graphviz
          else
            echo "UPLOAD_DOCUMENTATION=false" >> $GITHUB_ENV
          fi
      - name: Download MuJoCo
        run: |
          set -e
          set -x
          cd ${{ github.workspace }}/.. # Note that everything under ${{ github.workspace }} is cleaned by actions/checkout.
          wget https://github.com/deepmind/mujoco/releases/download/${{ matrix.mujoco-version }}/mujoco-${{ matrix.mujoco-version }}-linux-x86_64.tar.gz
          tar -zxvf mujoco-${{ matrix.mujoco-version }}-linux-x86_64.tar.gz
      - name: Checkout repository code
        if: matrix.standalone == 'standalone'
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Standalone build
        if: matrix.standalone == 'standalone'
        uses: jrl-umi3218/github-actions/build-cmake-project@master
        with:
          build-type: ${{ matrix.build-type }}
          options: -DMUJOCO_ROOT_DIR=${{ github.workspace }}/../mujoco-${{ matrix.mujoco-version }}
      - name: Colcon build
        if: matrix.standalone == 'colcon'
        uses: jrl-umi3218/github-actions/build-colcon-project@master
        with:
          build-type: ${{ matrix.build-type }}
          cmake-args: -DMUJOCO_ROOT_DIR=${{ github.workspace }}/../mujoco-${{ matrix.mujoco-version }} -DINSTALL_DOCUMENTATION=${{ env.UPLOAD_DOCUMENTATION }} -DUSE_ROS2=True
          catkin-test-args: --no-deps
          build-packages: mujoco_tactile_sensor_plugin
          skip-test: true